spring:
  application:
    name: stock-portfolio-tracker


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portfolio-tracker?autoReconnect=true
    username: root
    password: password

  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8087
